ALTER TABLE candidates ADD COLUMN IF NOT EXISTS preferred_name text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS address_suburb text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS address_postcode text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS nearest_airport text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS emergency_contact_relationship text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS current_employer text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS home_employment_type text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS max_block_length int;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS start_notice_days int;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS excluded_states text[] DEFAULT '{}';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS excluded_facilities text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS preferred_accommodation_type text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS willing_to_drive boolean DEFAULT false;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS partner_family_details text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS certifications text[] DEFAULT '{}';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS emr_systems text[] DEFAULT '{}';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS years_travel_nursing int;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS previous_agencies text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS highest_qualification text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS specialisation_notes text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS payment_type text DEFAULT 'PAYG';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS abn_number text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS state_increments jsonb DEFAULT '{}';
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS blacklisted_facilities text;
ALTER TABLE candidates ADD COLUMN IF NOT EXISTS admin_notes text;
